site_name: CampusConnect Functional Documentation
theme:
  name: material

  features:
    - content.code.copy
    - content.tabs.link
    - content.tooltips

nav:
  - Overview: index.md
  - Functional Use Cases: use_cases.md
  - Business Use Cases: business_useCases.md
  - Modules: modules.md
  - High Level Architecture: architecture.md
  - Project Flow: Project_flow.md
  - DFD: DFD.md
  - System architecture: structural_diagram.md
  - Database Schema:
      - ER Diagram: er_diagram.md
  - Test Case Documentations:
      - Signup Module: signup_test.md
      - Login Module: login_test.md
  - CI/CD Pipeline and Deployment Flow:
      - Code Merge Workflow: code_merge_workflow.md
      - Security scanning (SAST, DAST): security_scanning.md

plugins:
  - mermaid2
